# This is a basic workflow that is manually triggered

name: Build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
    - master
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow builds the java classes
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Get classes list
        run: |
          find ./src/ -type f -name "*.java" > sources 

      - name: Compile
        run: |
          mkdir ./out/
          javac ./out/ @sources 

      - name: Test Javadoc
        run: | 
          javadoc -sourcepath ./src/ -d ./docs -subpackages Exceptions Game Manager UI;
          rm -r ./docs/
            
    
  
